---
abstract: 'Perl pragma to declare constants'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant-tiny
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  repository: https://github.com/maddingue/constant-tiny
version: 1.01
