---
abstract: 'Perl pragma to declare constants'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant-tiny
provides:
  constant::tiny:
    file: lib/constant/tiny.pm
    version: 1.00
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/maddingue/constant-tiny
version: 1.00
